"use client";

import { useEffect, useMemo, useState, type ReactNode } from "react";
import {
  Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart,
  Radar, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis,
  ResponsiveContainer, Tooltip, XAxis, YAxis,
} from "recharts";

type Data = { demo?: boolean; summary: { total_responses: number; unique_respondents: number; overall_average: number | string | null; latest_response: string | null }; yearLevels: { label: string; value: number }[]; questions: { question: string; average: number | string }[]; feedback: { id: number; year_level: string | null; feedback: string; created_at: string }[] };
const n = (v: number | string | null | undefined) => Number(v ?? 0);
const fmt = (v: string | null) => v ? new Intl.DateTimeFormat("th-TH", { dateStyle: "medium", timeStyle: "short" }).format(new Date(v)) : "-";
const palette = ["#6d8cff", "#9b82ff", "#38d9b0", "#f5b968", "#f47eaa", "#7e8da8"];

export default function Home() {
  const [data, setData] = useState<Data | null>(null); const [error, setError] = useState(""); const [active, setActive] = useState("ภาพรวม");
  useEffect(() => { fetch("/api/dashboard", { cache: "no-store" }).then(async r => { const x = await r.json(); if (!r.ok) throw new Error(x.error); setData(x); }).catch(e => setError(e instanceof Error ? e.message : "โหลดข้อมูลไม่สำเร็จ")); }, []);
  const insight = useMemo(() => { const q = data?.questions ?? []; const sorted = [...q].sort((a, b) => n(b.average) - n(a.average)); return { avg: n(data?.summary.overall_average), best: sorted[0]?.question ?? "-", low: sorted.at(-1)?.question ?? "-" }; }, [data]);
  if (!data && !error) return <main className="loading-screen"><div className="loader" /><p>กำลังเตรียมรายงานของคุณ...</p></main>;
  if (!data) return <main className="loading-screen"><div className="error-box"><b>โหลดข้อมูลไม่สำเร็จ</b><span>{error}</span><small>ตรวจสอบ DATABASE_URL และตาราง survey_responses</small></div></main>;
  const levels = data.yearLevels.map((x, i) => ({ ...x, fill: palette[i % palette.length] }));
  const menu = ["ภาพรวม", "ผลการประเมิน", "ผู้ตอบแบบสอบถาม", "ความคิดเห็น"];
  return <main className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">S</span><div><strong>SurveyDash</strong><small>ANALYTICS CENTER</small></div></div><div className="search">⌕ <span>ค้นหาเมนู...</span><kbd>⌘ K</kbd></div><p className="eyebrow">เมนูหลัก</p><nav>{menu.map((x, i) => <button key={x} className={`nav-item ${active === x ? "active" : ""}`} onClick={() => setActive(x)}><i>{["⌂", "▥", "◌", "≡"][i]}</i>{x}<em>{active === x ? "›" : ""}</em></button>)}</nav><p className="eyebrow manage">จัดการ</p><nav><button className="nav-item"><i>⚙</i>ตั้งค่า</button><button className="nav-item"><i>?</i>ช่วยเหลือ</button></nav><div className="sidebar-foot"><span className="status-dot" /><div><b>ฐานข้อมูลเชื่อมต่อแล้ว</b><small>{data.demo ? "Demo mode" : "Live · อัปเดตอัตโนมัติ"}</small></div></div></aside>
    <section className="workspace"><header className="topbar"><div><p className="crumb">Dashboard <span>/</span> {active}</p><h1>ภาพรวมแดชบอร์ด</h1><p className="muted">รายงานภาพรวมข้อมูลแบบสอบถามทั้งหมด · อัปเดต {fmt(data.summary.latest_response)}</p></div><div className="top-actions"><button className="period">2024 — 2025⌄</button><button className="refresh" onClick={() => window.location.reload()}>↻ <span>รีเฟรชข้อมูล</span></button><div className="avatar">NP</div></div></header>
      <div className="content"><section className="metrics"><Metric label="แบบสอบถามทั้งหมด" value={data.summary.total_responses.toLocaleString()} note="รายการที่บันทึกในระบบ" tone="blue" icon="↗" /><Metric label="ผู้ตอบแบบสอบถาม" value={data.summary.unique_respondents.toLocaleString()} note="เชื่อมกับจำนวนแบบสอบถาม" tone="purple" icon="◉" /><Metric label="คะแนนเฉลี่ยรวม" value={`${insight.avg.toFixed(2)} / 5`} note={`คำถามเด่น ${insight.best}`} tone="green" icon="✦" /><Metric label="คำถามที่วิเคราะห์" value={`${data.questions.length} ข้อ`} note={`ควรติดตาม ${insight.low}`} tone="orange" icon="▥" /></section>
        <section className="grid-main"><Panel title="แนวโน้มคะแนนเฉลี่ย" subtitle="ค่าเฉลี่ยของคำถาม Q1 — Q14" action="ภาพรวม"><Chart className="chart-large"><AreaChart data={data.questions}><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#6d8cff" stopOpacity=".42" /><stop offset="1" stopColor="#6d8cff" stopOpacity="0" /></linearGradient></defs><CartesianGrid vertical={false} stroke="#fff" strokeOpacity={.06} /><XAxis dataKey="question" axisLine={false} tickLine={false} tick={{ fill: "#71809d", fontSize: 11 }} /><YAxis domain={[0, 5]} axisLine={false} tickLine={false} tick={{ fill: "#71809d", fontSize: 11 }} /><Tooltip contentStyle={{ background: "#151c2b", border: "1px solid #334155", borderRadius: 10 }} formatter={(v) => [`${n(v as number).toFixed(2)} / 5`, "คะแนนเฉลี่ย"]} /><Area type="monotone" dataKey="average" stroke="#6d8cff" strokeWidth={3} fill="url(#fill)" /></AreaChart></Chart></Panel><Panel title="ผู้ตอบตามระดับชั้น" subtitle="สัดส่วนผู้ตอบทั้งหมด"><div className="chart-donut"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={levels} dataKey="value" nameKey="label" innerRadius={62} outerRadius={91} paddingAngle={3}>{levels.map(x => <Cell key={x.label} fill={x.fill} stroke="none" />)}</Pie><Tooltip contentStyle={{ background: "#151c2b", border: "1px solid #334155", borderRadius: 10 }} /></PieChart></ResponsiveContainer><div className="donut-total"><b>{data.summary.unique_respondents.toLocaleString()}</b><span>ผู้ตอบทั้งหมด</span></div></div><div className="legend">{levels.map(x => <div key={x.label}><span><i style={{ background: x.fill }} />{x.label}</span><b>{x.value.toLocaleString()}</b></div>)}</div></Panel></section>
        <section className="grid-bottom"><Panel title="คะแนนเฉลี่ยรายข้อ" subtitle="เปรียบเทียบผลลัพธ์ Q1 — Q14" action="ดูรายละเอียด"><Chart className="chart-bar"><BarChart data={data.questions} barSize={17}><CartesianGrid vertical={false} stroke="#fff" strokeOpacity={.06} /><XAxis dataKey="question" axisLine={false} tickLine={false} tick={{ fill: "#71809d", fontSize: 10 }} /><YAxis domain={[0, 5]} axisLine={false} tickLine={false} tick={{ fill: "#71809d", fontSize: 10 }} /><Tooltip contentStyle={{ background: "#151c2b", border: "1px solid #334155", borderRadius: 10 }} formatter={(v) => [`${n(v as number).toFixed(2)} / 5`, "คะแนนเฉลี่ย"]} /><Bar dataKey="average" fill="#927df1" radius={[5, 5, 0, 0]} /></BarChart></Chart></Panel><Panel title="โปรไฟล์คะแนน" subtitle="ภาพรวมทั้ง 14 คำถาม"><div className="radar-chart"><ResponsiveContainer width="100%" height="100%"><RadarChart data={data.questions}><PolarGrid stroke="#334155" /><PolarAngleAxis dataKey="question" tick={{ fill: "#8997b2", fontSize: 10 }} /><PolarRadiusAxis domain={[0, 5]} tick={false} axisLine={false} /><Radar dataKey="average" stroke="#38d9b0" fill="#38d9b0" fillOpacity={.2} strokeWidth={2} /></RadarChart></ResponsiveContainer></div><div className="score-row"><span>ค่าเฉลี่ยรวม</span><b>{insight.avg.toFixed(2)}<small> / 5</small></b></div></Panel><Panel title="สรุปผลการประเมิน" subtitle="จุดเด่นและโอกาสในการพัฒนา"><div className="insights"><Insight label="คะแนนสูงสุด" value={insight.best} description="คำถามที่ได้คะแนนดีที่สุด" color="green" /><Insight label="คะแนนต่ำสุด" value={insight.low} description="หัวข้อที่ควรติดตาม" color="orange" /><Insight label="ข้อมูลล่าสุด" value={data.summary.total_responses.toLocaleString()} description="รายการตอบแบบสอบถาม" color="blue" /></div></Panel></section>
        <section className="bottom-strip"><Panel title="ความคิดเห็นล่���สุด" subtitle="เสียงจากผู้ตอบแบบสอบถาม"><div className="comments">{data.feedback.slice(0, 6).map(x => <article key={x.id}><p>“{x.feedback}”</p><small>{x.year_level || "ไม่ระบุระดับชั้น"} · {fmt(x.created_at)}</small></article>)}{!data.feedback.length && <span className="muted">ยังไม่มีความคิดเห็น</span>}</div></Panel></section>
      </div></section></main>;
}
function Chart({ children, className }: { children: ReactNode; className: string }) { return <div className={className}><ResponsiveContainer width="100%" height="100%">{children as React.ReactElement}</ResponsiveContainer></div>; }
function Metric({ label, value, note, tone, icon }: { label: string; value: string; note: string; tone: string; icon: string }) { return <div className={`metric ${tone}`}><div className="metric-head"><span>{label}</span><i>{icon}</i></div><strong>{value}</strong><small>{note}</small></div>; }
function Panel({ title, subtitle, action, children }: { title: string; subtitle: string; action?: string; children: ReactNode }) { return <section className="panel"><header><div><h2>{title}</h2><p>{subtitle}</p></div>{action && <button>{action}⌄</button>}</header>{children}</section>; }
function Insight({ label, value, description, color }: { label: string; value: string; description: string; color: string }) { return <div className="insight"><div><span>{label}</span><small>{description}</small></div><b className={color}>{value}</b></div>; }
